steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_REGION-docker.pkg.dev/$PROJECT_ID/qsurvey-online/qsurvey-online:$_TAG", "."]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_REGION-docker.pkg.dev/$PROJECT_ID/qsurvey-online/qsurvey-online:$_TAG"]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image=$_REGION-docker.pkg.dev/$PROJECT_ID/qsurvey-online/qsurvey-online:$_TAG
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated
      - --port=6060
      - --set-env-vars=NODE_ENV=production
      - --set-secrets=MONGO_URI=MONGO_URI:latest
      - --set-secrets=GOOGLE_CLIENTID=GOOGLE_CLIENTID:latest
      - --set-secrets=GOOGLE_SECRET=GOOGLE_SECRET:latest
      - --set-secrets=SECRET=SECRET:latest
      - --set-secrets=REDIRECT_URL=REDIRECT_URL:latest
      - --set-secrets=FRONTEND_URL=FRONTEND_URL:latest
      - --min-instances=1
      - --memory=1Gi

substitutions:
  _TAG: "latest"
  _SERVICE: "qsurvey-online"
  _REGION: "us-central1"

images:
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/qsurvey-online/qsurvey-online:$_TAG"
